export const DISCOUNTS = {
  TEN_PERCENT_DISCOUNT: 10,
  TWENTY_PERCENT_DISCOUNT: 20,
  THIRTY_PERCENT_DISCOUNT: 30,
  FORTY_PERCENT_DISCOUNT: 40,
  FIFTY_PERCENT_DISCOUNT: 50,
} as const;

export type Discounts = (typeof DISCOUNTS)[keyof typeof DISCOUNTS];

console.log(DISCOUNTS.TEN_PERCENT_DISCOUNT);
